"""
agent_model_gen.py — 연산 조합 → PyTorch 모델 코드 자동 생성
"""
import tempfile
import importlib.util
from pathlib import Path
from agent_strategy import combo_id, CONTRACTION, ELEMENTWISE

CONTRACTION_CODE = {
    "gemm": {
        "init":    "self.linear_{i} = torch.nn.Linear(dim, dim, bias=False)",
        "forward": "x = self.linear_{i}(x)",
        "input":   "(1, {dim})",
    },
    "batch_gemm": {
        "init":    "self.linear_{i} = torch.nn.Linear(dim, dim, bias=False)",
        "forward": "x = torch.bmm(x, self.linear_{i}.weight.t().unsqueeze(0).expand(x.size(0), -1, -1))",
        "input":   "(2, {dim}, {dim})",
    },
    "gemv": {
        "init":    "self.weight_{i} = torch.nn.Parameter(torch.randn(dim, dim))",
        "forward": "x = torch.mv(self.weight_{i}, x.squeeze(0)).unsqueeze(0)",
        "input":   "(1, {dim})",
    },
    "dot_product": {
        "init":    "self.weight_{i} = torch.nn.Parameter(torch.randn(dim))",
        "forward": "x = torch.matmul(x, self.weight_{i}.unsqueeze(-1)).expand(-1, {dim})",
        "input":   "(1, {dim})",
    },
}

ELEMENTWISE_CODE = {
    "add":     "x = x + x",
    "sub":     "x = x - x * 0.5",
    "mul":     "x = x * x",
    "div":     "x = x / (x.abs() + 1.0)",
    "rsqrt":   "x = torch.rsqrt(x * x + 1e-6)",
    "sqrt":    "x = torch.sqrt(x * x + 1e-6)",
    "exp":     "x = torch.exp(x.clamp(-10, 10))",
    "sigmoid": "x = torch.sigmoid(x)",
    "tanh":    "x = torch.tanh(x)",
    "sin":     "x = torch.sin(x)",
    "cos":     "x = torch.cos(x)",
    "pow2":    "x = torch.pow(x, 2.0)",
}

def generate_model_code(ops: list, dim: int = 64) -> str:
    cid = combo_id(ops)
    has_batch = ops[0] == "batch_gemm"

    init_lines = []
    forward_lines = []
    contraction_idx = 0

    for op in ops:
        if op in CONTRACTION:
            tmpl = CONTRACTION_CODE[op]
            init_lines.append("        " + tmpl["init"].format(i=contraction_idx, dim=dim))
            forward_lines.append("        " + tmpl["forward"].format(i=contraction_idx, dim=dim))
            contraction_idx += 1
        elif op in ELEMENTWISE:
            forward_lines.append("        " + ELEMENTWISE_CODE[op])

    init_block = "\n".join(init_lines) if init_lines else "        pass"
    forward_block = "\n".join(forward_lines)

    if has_batch:
        input_code = f"torch.randn(2, {dim}, {dim})"
    else:
        input_code = f"torch.randn(1, {dim})"

    return f'''\
"""
AUTO-GENERATED by RNGD Agent
combo: {" → ".join(ops)}
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = {dim}):
        super().__init__()
{init_block}

    def forward(self, x: torch.Tensor) -> torch.Tensor:
{forward_block}
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return ({input_code},)
'''


def save_model(ops: list, out_dir: Path = Path("models"), dim: int = 64) -> Path:
    cid = combo_id(ops)
    path = out_dir / f"agent_{cid}.py"
    path.write_text(generate_model_code(ops, dim), encoding="utf-8")
    return path


def validate_model(ops: list, dim: int = 64) -> tuple[bool, str]:
    """임시 파일로 저장 후 torch_mlir 컴파일 가능 여부 검증"""
    import torch, torch_mlir

    code = generate_model_code(ops, dim)
    with tempfile.NamedTemporaryFile(
        mode='w', suffix='.py', delete=False, dir='/tmp', prefix='rngd_agent_'
    ) as f:
        f.write(code)
        tmp_path = f.name

    try:
        spec = importlib.util.spec_from_file_location("agent_tmp", tmp_path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        model = mod.get_model().eval()
        inputs = mod.get_sample_inputs()
        torch_mlir.compile(model, inputs, output_type='linalg-on-tensors')
        return True, ""
    except Exception as e:
        return False, str(e)[:200]
    finally:
        Path(tmp_path).unlink(missing_ok=True)


if __name__ == "__main__":
    import sys
    test_cases = [
        ["gemm", "sigmoid"],
        ["gemm", "tanh", "gemm"],
        ["gemm", "sigmoid", "gemm", "exp"],
        ["batch_gemm", "sin", "batch_gemm", "cos"],
        ["gemv", "sqrt"],
        ["dot_product", "tanh", "gemm"],
    ]
    for ops in test_cases:
        valid, err = validate_model(ops)
        status = "✅ VALID" if valid else f"❌ INVALID: {err[:80]}"
        print(f"  {' → '.join(ops):<45} {status}")
