"""
AUTO-GENERATED by RNGD Agent
combo: gemv → pow2 → gemv → tanh
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = 64):
        super().__init__()
        self.weight_0 = torch.nn.Parameter(torch.randn(dim, dim))
        self.weight_1 = torch.nn.Parameter(torch.randn(dim, dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.mv(self.weight_0, x.squeeze(0)).unsqueeze(0)
        x = torch.pow(x, 2.0)
        x = torch.mv(self.weight_1, x.squeeze(0)).unsqueeze(0)
        x = torch.tanh(x)
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return (torch.randn(1, 64),)
