"""
AUTO-GENERATED by RNGD Agent
combo: gemm → exp → dot_product → tanh
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = 64):
        super().__init__()
        self.linear_0 = torch.nn.Linear(dim, dim, bias=False)
        self.weight_1 = torch.nn.Parameter(torch.randn(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.linear_0(x)
        x = torch.exp(x.clamp(-10, 10))
        x = torch.matmul(x, self.weight_1.unsqueeze(-1)).expand(-1, 64)
        x = torch.tanh(x)
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return (torch.randn(1, 64),)
