"""
AUTO-GENERATED by RNGD Agent
combo: batch_gemm → sqrt → gemm → div
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = 64):
        super().__init__()
        self.linear_0 = torch.nn.Linear(dim, dim, bias=False)
        self.linear_1 = torch.nn.Linear(dim, dim, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.bmm(x, self.linear_0.weight.t().unsqueeze(0).expand(x.size(0), -1, -1))
        x = torch.sqrt(x * x + 1e-6)
        x = self.linear_1(x)
        x = x / (x.abs() + 1.0)
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return (torch.randn(2, 64, 64),)
