"""
AUTO-GENERATED by RNGD Agent
combo: gemm → exp → gemm → exp
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = 64):
        super().__init__()
        self.linear_0 = torch.nn.Linear(dim, dim, bias=False)
        self.linear_1 = torch.nn.Linear(dim, dim, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = self.linear_0(x)
        x = torch.exp(x.clamp(-10, 10))
        x = self.linear_1(x)
        x = torch.exp(x.clamp(-10, 10))
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return (torch.randn(1, 64),)
