"""
AUTO-GENERATED by RNGD Agent
combo: dot_product → pow2 → dot_product → sigmoid
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = 64):
        super().__init__()
        self.weight_0 = torch.nn.Parameter(torch.randn(dim))
        self.weight_1 = torch.nn.Parameter(torch.randn(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.matmul(x, self.weight_0.unsqueeze(-1)).expand(-1, 64)
        x = torch.pow(x, 2.0)
        x = torch.matmul(x, self.weight_1.unsqueeze(-1)).expand(-1, 64)
        x = torch.sigmoid(x)
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return (torch.randn(1, 64),)
