"""
AUTO-GENERATED by RNGD Agent
combo: gemv → sigmoid → gemm → exp
"""
import torch


class AgentModel(torch.nn.Module):
    def __init__(self, dim: int = 64):
        super().__init__()
        self.weight_0 = torch.nn.Parameter(torch.randn(dim, dim))
        self.linear_1 = torch.nn.Linear(dim, dim, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = torch.mv(self.weight_0, x.squeeze(0)).unsqueeze(0)
        x = torch.sigmoid(x)
        x = self.linear_1(x)
        x = torch.exp(x.clamp(-10, 10))
        return x


def get_model():
    return AgentModel()


def get_sample_inputs():
    return (torch.randn(1, 64),)
